Задаине 1
purchases = int (input("Введите количество покупок >>>"))

if purchases <= 5:
    print("Заказ сделать не возможно")
if purchases >= 25:
    print("Заказ будет идти со скидкой")
else:
    print("Можно заказать")
    
Задаине 2   
h = 1
m = 60
s = 3600
f"{h}:{m}^{s}".format(h, m, s)

time = int(input("Введите время в секндах"))
h = time // 3600
m = (time - h * 3600) // 60
s = time - (h * 3600 + m * 60)
print(f"Время в формате чч:мм:сс {h} : {m} : {s}")

Задаине 3
n = int(input("Введите число n: "))
temp = str(n)
t1 = temp + temp
t2 = temp + temp + temp
comp = n + int(t1) + int(t2)
print("Результат равен:", comp)

Задаине 4
number = abs( int(input("введите целое положительное число")))
max = number % 10
while number >= 1:
    number = number // 10
    if number % 10 > max:
        max = number % 10
    if number > 9:
        continue
    else:
        print("Самая большая цифра в числе", max)
        
Задаине 5        
profit = float(input("Введите выручку фирмы "))
costs = float(input("Введите издержки фирмы "))
if profit > costs:
    print(f"Фирма работает с прибылью. Рентабельность выручки составила {profit / costs:.2f}")
    workers = int(input("Введите количество сотрудников фирмы "))
    print(f"прибыль в расчете на одного сторудника сотавила {profit / workers:.2f}")
elif profit == costs:
    print("Фирма работает в ноль")
else:
    print("Фирма работает в убыток")
        break

Задаине 6
a = int(input("Введите результаты пробежки первого дня"))
b = int(input("Желаемый результат в км"))
days = 1
km = a
while km < b:
    a = a + 0.1 * a
    days += 1
    km = km + a
    print(f"Достижение требуемых показателей на % d" % days)
